- client/qbittorrent.go
Fixes API support for qBittorrent 5.0.2
> fix(qbittorent): remove extra `apiVersion` validation

- hardlinkfilemap/hardlinkfilemap.go
This fixes the issue where the system was trying to stat files from incomplete torrents, resulting in unnecessary warning messages.
No need to merge if a big refactor is being worked on. But adding it here for the sake of useful information.
> fix(hardlink): skip incomplete torrents

- config/torrent.go
Taken from qbitmanage and qbittools
https://github.com/StuffAnThings/qbit_manage/blob/master/modules/util.py#L67-L101
https://gitlab.com/AlexKM/qbittools/-/blob/master/commands/tagging.py?ref_type=heads#L26-47
> feat(torrent): expand unregisteredStatuses

- README.md
- client/qbittorrent.go
- config/torrent.go
- tracker/hdb.go
- tracker/ops.go
- tracker/red.go
- tracker/struct.go
- tracker/tracker.go
- tracker/unit3d.go
This adds API check fallback if no match is found in `unregisteredStatuses` for the following:
- UNIT3D Generic **(Requires a torrent URL to be present in `Torrent Comment`)**
- RED
- OPS
- HDB
Currently untested, as I don't have any unregistered torrents.
> feat(tracker): add RED, HDB, OPS, UNIT3D

- config/torrent.go
`stream truncated` is typical for trackers that are down. E.g. BLU and FL.
> fix(torrent): disable match on "truncated"

- README.md
- config/torrent.go
- logger/log.go
- Added `HasMissingFiles()` helper function to detect torrents with missing files on disk
This feature helps identify torrents where the files have been deleted or moved without the torrent client's knowledge. This is particularly useful for:
- Detecting accidental file deletions
- Finding torrents that need rechecking
- Cleanup of torrents where data is no longer available
Add to your config.yaml:
```yaml
tag:
- name: missing-files
mode: full
update:
- HasMissingFiles()
```
> feat(torrent): add helper to detect missing files

- README.md
- tracker/btn.go
- tracker/struct.go
- tracker/tracker.go
Depends on a torrentID in the `Tracker Comment`, which they started doing last year.
> feat(tracker): add BTN

- README.md
- client/deluge.go
- cmd/clean.go
- cmd/relabel.go
- cmd/retag.go
- Update README to clarify free space path behavior for different clients
- Modify Deluge client to validate free space path input
- Update clean, relabel, and retag commands to handle qBittorrent free space checks
Testing just fine with my qbit and deluge instances.
Program will now exit early if `FreeSpaceGB()` and/or `FreeSpaceSet()` is used in a config and `free_space_path` is not set for Deluge.
> fix: path check for Deluge when using FreeSpaceGB

- cmd/helpers.go
Fixed the order, so it doesn't try to stat files *after* they've been deleted.
The bug:
```
[2025-03-03T17:42:46+01:00]  INFO clean          : removing: "Lovely.Runner.2024.S01.1080p.Viki.WEB-DL.AAC2.0.x264-unco@AvistaZ" - 9.6 GiB
[2025-03-03T17:42:46+01:00]  INFO clean          : Ratio: 19.298 / Seed days: 276.257 / Seeds: 107 / Label: sonarrkorean-imported / Tags:  / Tracker: avistaz.to / Tracker Status: ""
[2025-03-03T17:42:51+01:00]  INFO clean          : Removed
[2025-03-03T17:42:52+01:00]  WARN hardlinkfilemap: Failed to stat file: /mnt/local/downloads/torrents/qbittorrent/completed/Lovely.Runner.2024.S01.1080p.Viki.WEB-DL.AAC2.0.x264-unco@AvistaZ/Lovely.Runner.2024.S01E01.1080p.Viki.WEB-DL.AAC2.0.x264-unco@Avistaz.mkv - stat …
```
> fix(clean): update hardlink map before file deletion

- README.md
- cmd/clean.go
- cmd/helpers.go
- config/filter.go
Users can now optionally keep data on disk when running `clean`. Default behaviour will be`delete_data: true` for backwards compatibility.
> feat(clean): optionally keep data

- config/torrent.go
This one is causing too many false positives.
> fix: remove "not found" from unregisteredStatuses

- httputils/retryclient.go
No need to hit the APIs 10 times if they are down.
> fix(retryclient): reduce maximum retries from 10 to 1

- README.md
Use explicit comparison for `IsPrivate` and `IsPublic` in examples like stated [here](https://github.com/autobrr/tqm?tab=readme-ov-file#filtering-by-privatepublic-status)
> fix(readme): use explicit comparison for IsPrivate in examples

- README.md
Removes the additional start for a yaml code block from the config example code block.
> fix(docs): config example code block

- go.mod
- go.sum
- pkg/client/qbittorrent.go
Implement new `includeTrackers` on torrent list fetch to include trackers in a single call, or fall back to fetch per torrent.
> feat(qbit): include trackers with torrents list or fallback to fetch

- cmd/orphan.go
This changes the counters in the `orphan` command to be of the type `atomic.Uint*` to make use of the `Uint*.Add` functions that are suggested in the `atomic` docs.
> refactor(orphan): use atomic.Uint types for counters

- cmd/clean.go
- cmd/helpers.go
- cmd/orphan.go
- cmd/pause.go
- cmd/relabel.go
- cmd/retag.go
- go.mod
- go.sum
- pkg/client/deluge.go
- pkg/client/interface.go
- pkg/client/qbittorrent.go
- pkg/client/tagInterface.go
- pkg/config/torrent.go
- pkg/expression/check.go
- pkg/expression/compile.go
- pkg/tracker/bhd.go
- pkg/tracker/btn.go
- pkg/tracker/hdb.go
- pkg/tracker/interface.go
- pkg/tracker/ops.go
- pkg/tracker/ptp.go
- pkg/tracker/red.go
- pkg/tracker/unit3d.go
Pass context to all external calls like torrent clients and tracker requests.
> refactor: pass context to external calls

- pkg/httputils/retryclient.go
- pkg/tracker/bhd.go
- pkg/tracker/btn.go
- pkg/tracker/hdb.go
- pkg/tracker/ops.go
- pkg/tracker/ptp.go
- pkg/tracker/red.go
- pkg/tracker/unit3d.go
Avoids leaking API tokens when used as part of the url.... looking at you BHD.
> refactor(tracker): remove logging from httputils

- pkg/notification/discord.go
Removed escaping for titles that have markdown formatting characters, because formatting is disabled there. It currently leads to something like this:
`[Saizen]\_Kuroko's\_Basketball\_-\_56\_[1080p][Blu-Ray][89693BBE].mkv` which should be
`[Saizen]_Kuroko's_Basketball_-_56_[1080p][Blu-Ray][89693BBE].mkv`.
> fix(notifications): don't escape discord embed titles

- cmd/helpers.go
- pkg/client/qbittorrent.go
- pkg/client/tagInterface.go
Avoids an edge case where tags get listed multiple times by avoiding using a slice in the ShouldRetag function.
> fix(retag): avoid tag duplicates by using maps

- cmd/helpers.go
- pkg/config/torrent.go
- pkg/tracker/bhd.go
- pkg/tracker/btn.go
- pkg/tracker/hdb.go
- pkg/tracker/ops.go
- pkg/tracker/ptp.go
- pkg/tracker/red.go
- pkg/tracker/struct.go
- pkg/tracker/unit3d.go
> fix(api): print torrent logs divider in API calls to preserve grouping

- cmd/helpers.go
- pkg/client/qbittorrent.go
- pkg/client/tagInterface.go
This implements the SetTags endpoint added in qBit WebAPI version 2.11.4 and should provide a significant performance improvement when updating tags for a ton of torrents.
> perf(qbit): use SetTags if API version is supported

- pkg/config/torrent.go
- pkg/httputils/httputils.go
- pkg/tracker/bhd.go
- pkg/tracker/btn.go
- pkg/tracker/hdb.go
- pkg/tracker/ops.go
- pkg/tracker/ptp.go
- pkg/tracker/red.go
- pkg/tracker/unit3d.go
This updates the approach to API requests for every tracker that is currently definable in the config.
It removes the `rek` dependency and brings them all in line to be more consistent.
> refactor(tracker): clean up API requests

- README.md
- cmd/retag.go
- pkg/client/qbittorrent.go
Add `create_tags_upfront` config option for qBittorrent clients to control tag pre-creation.
- Defaults to `true` for backward compatibility
- When `false`, only creates tags when applying them to torrents
- Prevents empty tags in qBittorrent
Fixes #74
> feat(retag): make tag creation configurable to prevent empty tags

- README.md
- pkg/client/qbittorrent.go
- pkg/config/torrent.go
Resolves https://github.com/autobrr/tqm/issues/82
Test performed with the following config:
```yaml
clients:
qbt:
download_path: /home/user/Downloads
enabled: true
filter: default
type: qbittorrent
url: http://127.0.0.1:8080
notifications:
filters:
default:
tag:
- name: inactive-10mins
mode: add
update:
- LastActivitySeconds > 600
```
Results:
1. When item's last activity was <10 minutes ago: `Ignored torrents: 1, Retagged torrents: 0, 0 failures`
2. When item's last activity was >10 minutes ago: `Ignored torrents: 0, Retagged torrents: 1, 0 failures`. Confirmed that tag **inactive-10mins** was automatically added.
> feat(qbit): add key_torrent_last_activity_time
